name: Test Self-Hosted Runner with Docker

on: [push, pull_request]

jobs:
  test-runner:
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print System Info
        run: uname -a

      - name: List Files
        run: ls -alh

      - name: Build Docker Image
        run: |
          docker build -t my-app:latest .

      - name: Run Docker Container
        run: |
          docker run --rm my-app:latest
